### ISSUE TITLE
compile error on ubuntu20.04

### ISSUE THREAD

**Issue by yeyueluke** [fetty31/LieOdyssey#2]
when compile on ubuntu 20.04 ,it gives out error : 
LieOdyssey/cpp/build/_deps/manif-src/include/manif/impl/tangent_base.h:14:10: fatal error: tl/optional.hpp: 没有那个文件或目录
   14 | #include <tl/optional.hpp>

fix this need todo :
sudo mkdir -p /usr/local/include/tl
sudo wget https://raw.githubusercontent.com/TartanLlama/optional/master/include/tl/optional.hpp -O /usr/local/include/tl/optional.hpp
